# Generated by Django 5.2.7 on 2026-02-02 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('code_medecin', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('nom_medecin', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('num_patient', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nom_patient', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('code_specialite', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('nom_specialite', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id_consultation', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('compteur', models.IntegerField(blank=True, unique=True)),
                ('motif', models.CharField(max_length=50)),
                ('diagnostic', models.CharField(max_length=100)),
                ('prescription', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('date_medecin', models.SlugField(blank=True, unique=True)),
                ('date_patient', models.SlugField(blank=True, unique=True)),
                ('consult_code_medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionConsultation.medecin')),
                ('consult_num_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionConsultation.patient')),
            ],
        ),
        migrations.AddField(
            model_name='medecin',
            name='specialite_medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionConsultation.specialite'),
        ),
    ]
