# Generated by Django 5.2.7 on 2026-02-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionConsultation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='compteur',
            field=models.IntegerField(blank=True, default=0, unique=True),
        ),
    ]
