# Generated by Django 5.2.7 on 2026-02-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionConsultation', '0002_alter_consultation_compteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialite',
            name='nom_specialite',
            field=models.CharField(max_length=50),
        ),
    ]
